version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: rooms-backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: ./.docker/mysql
    container_name: rooms-mysql
    # restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=rooms_mysql
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_HOST=localhost
